services:
  bbqueue:
    image: bbqueue
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
  database:
      image: postgres
      environment:
        POSTGRES_USER: bbqueue_db
        POSTGRES_PASSWORD: bbqueue_db
        POSTGRES_DB: bbqueue
      volumes:
        - bbqueue_database:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
        interval: 10s
        retries: 3
        start_period: 30s
        timeout: 10s
  queue:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: bbqueue
      RABBITMQ_DEFAULT_PASS: bbqueue
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  bbqueue_database: